--se crea los roles de los usuarios
CREATE ROLE VENDEDOR_ROLE;
CREATE ROLE RESPVENTA_ROLE;
CREATE ROLE CAJERO_ROLE;
CREATE ROLE RESPCAJA_ROLE;
CREATE ROLE BODEGUERO_ROLE;
CREATE ROLE AUXBOD_ROLE;
CREATE ROLE RESPBOD_ROLE;
CREATE ROLE COMPRA_ROLE;
CREATE ROLE RESPCRED_ROLE;
CREATE ROLE ASISTGER_ROLE;
CREATE ROLE GERENTE_ROLE;
CREATE ROLE ADMIN_ROLE;

--Crea usuarios
-- Grupo VENTA
CREATE USER VENDEDOR1 FOR LOGIN VEND1;
CREATE USER VENDEDOR2 FOR LOGIN VEND2;
CREATE USER RESPVENTA FOR LOGIN RESPVENTA;
-- Grupo CAJA
CREATE USER CAJA1 FOR LOGIN CAJA1;
CREATE USER RESPONSABLECAJA FOR LOGIN RESPOCAJA;
-- Grupo BODEGA
CREATE USER BODEGA1 FOR LOGIN BOD1;
CREATE USER AUXILIARBOD1 FOR LOGIN AUXBOD1;
CREATE USER RESPBOD FOR LOGIN RESPOBOD;
-- Grupo COMPRADOR
CREATE USER COMPRA1 FOR LOGIN COMPRA1;
-- Grupo CREDITO
CREATE USER RESPONSABLEPCRED FOR LOGIN RESPOCRED;
-- Grupo GERENCIA
CREATE USER ASISTGER FOR LOGIN ASISTEGER;
CREATE USER GERENTE FOR LOGIN GERENTE;
-- DBA
CREATE USER ADMINDB FOR LOGIN ADMINSI;

-- Asignar usuarios a roles

-- Grupo VENTA
ALTER ROLE VENDEDOR_ROLE ADD MEMBER VEND1;
ALTER ROLE VENDEDOR_ROLE ADD MEMBER VEND2;
ALTER ROLE RESPVENTA_ROLE ADD MEMBER RESPVENTA;

-- Grupo CAJA
ALTER ROLE CAJERO_ROLE ADD MEMBER CAJA1;
ALTER ROLE RESPCAJA_ROLE ADD MEMBER RESPCAJA;

-- Grupo BODEGA
ALTER ROLE BODEGUERO_ROLE ADD MEMBER BOD1;
ALTER ROLE AUXBOD_ROLE ADD MEMBER AUXBOD1;
ALTER ROLE RESPBOD_ROLE ADD MEMBER RESPBOD;

-- Grupo COMPRADOR
ALTER ROLE COMPRA_ROLE ADD MEMBER COMPRA1;

-- Grupo CREDITO
ALTER ROLE RESPCRED_ROLE ADD MEMBER RESPCRED;

-- Grupo GERENCIA
ALTER ROLE ASISTGER_ROLE ADD MEMBER ASISTGER;
ALTER ROLE GERENTE_ROLE ADD MEMBER GERENTE;

-- DBA
ALTER ROLE ADMIN_ROLE ADD MEMBER ADMINDB;

-- Asignar permisos a los roles según las necesidades específicas de cada rol
-- Aquí tienes un ejemplo básico, pero deberás ajustar los permisos según los requisitos específicos.

-- Permisos para VENDEDOR_ROLE
GRANT SELECT, INSERT, UPDATE ON dbo.EmpresaComp TO VENDEDOR_ROLE;

-- Permisos para RESPVENTA_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EmpresaCom TO RESPVENTA_ROLE;

-- Permisos para CAJERO_ROLE
GRANT SELECT, INSERT ON dbo.EmpresaCom TO CAJERO_ROLE;

-- Permisos para RESPCAJA_ROLE
GRANT SELECT, INSERT, UPDATE ON dbo.EmpresaCom  TO RESPCAJA_ROLE;

-- Permisos para BODEGUERO_ROLE
GRANT SELECT, INSERT, UPDATE ON dbo.EmpresaCom  TO BODEGUERO_ROLE;

-- Permisos para AUXBOD_ROLE
GRANT SELECT, INSERT ON dbo.EmpresaCom  TO AUXBOD_ROLE;

-- Permisos para RESPBOD_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EmpresaCom TO RESPBOD_ROLE;

-- Permisos para COMPRA_ROLE
GRANT SELECT, INSERT, UPDATE ON dbo.EmpresaCom TO COMPRA_ROLE;

-- Permisos para RESPCRED_ROLE
GRANT SELECT, UPDATE ON dbo.EmpresaCom TO RESPCRED_ROLE;

-- Permisos para ASISTGER_ROLE
GRANT SELECT ON dbo.EmpresaCom TO ASISTGER_ROLE;

-- Permisos para GERENTE_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EmpresaCom TO GERENTE_ROLE;

-- Permisos para ADMIN_ROLE
GRANT CONTROL ON DATABASE::EmpresaCom TO ADMIN_ROLE